# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249bb4661f59b828280a2c08f152c7200cc011ab37399012b5a65f8f621f4deb5c7634a0f7b2d10e0b633a52341199bd993da61004a197cfe974c037c2ae2fbc

test:
  secret_key_base: 1f0cc6faf40ed31c94b859bc3183fcf280e6240f0d67fcf53ee7a7fa011d7b854f3b67ff42ebb3141191e5cf699130973ff560409e0094882ebf7282b1ad0f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
